name: Update Publications

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:
  # push:
  #   branches:
  #     - main 

jobs:
  update_publications:
    runs-on: ubuntu-latest
    environment:
      name: github-pages  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.7
    
    # - name: Install dependencies
    #   run: |
    #     gem install bundler
    #     bundle install
    
    - name: Fetch Data from ResearchMap
      run: |
        # Use curl to fetch data from the ResearchMap API
        API_RESPONSE=$(curl -s -X GET "https://api.researchmap.jp/kosuke-mitarai/published_papers")
        
        # Parse the JSON response using jq and extract relevant data
        PAPERS=$(echo "$API_RESPONSE" | jq -c '.items[]')
        
        # Generate Markdown content for your Jekyll site based on extracted data
        # Generate the content for the publications page
        echo "---" > publications.md
        echo "layout: page" >> publications.md
        echo "title: Publications" >> publications.md
        echo "---" >> publications.md
        echo "" >> publications.md
        # Loop through each extracted paper and add it to the content
        while read -r paper; do
          JOURNAL_NAME=$(echo "$paper" | jq -r '.publication_name.en')
          VOLUME=$(echo "$paper" | jq -r '.volume')
          STARTING_PAGE=$(echo "$paper" | jq -r '.starting_page')
          TITLE=$(echo "$paper" | jq -r '.paper_title.en')
          AUTHORS=$(echo "$paper" | jq -r '.authors.en | map(.name) | join(", ")')
          DOI=$(echo "$paper" | jq -r '.identifiers.doi[0]')
          
          echo "- [$TITLE](https://doi.org/$DOI), $AUTHORS, *$JOURNAL_NAME* **$VOLUME**, $STARTING_PAGE" >> publications.md
        done <<< "$PAPERS"

    - name: Commit and Push Changes
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add publications.md
        git commit -m "Update publications"
        git push origin main


    # - name: Build Jekyll Site
    #   run: bundle exec jekyll build
    
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     publish_dir: _site
